// <auto-generated />
using DatabaseAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseAccessLayer.Migrations
{
    [DbContext(typeof(KarinaDbContext))]
    partial class KarinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseAccessLayer.Models.MetricsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRevenuePerPayingUser")
                        .HasColumnType("numeric");

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("ClickThroughRate")
                        .HasColumnType("real");

                    b.Property<float>("ConversionRate")
                        .HasColumnType("real");

                    b.Property<decimal>("CostPerClick")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CostPerInstall")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustomerAcquisitionCost")
                        .HasColumnType("numeric");

                    b.Property<float>("LifetimeValue")
                        .HasColumnType("real");

                    b.Property<float>("ReturnOnMarketingInvestment")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
